AWSTemplateFormatVersion: '2010-09-09'
Description: Custom CloudFormation resource for copying objects between S3 buckets.

Resources:
  CopyS3Object:
    Type: AWS::Lambda::Function
    Properties:
          Handler: index.handler
          Role: !GetAtt CopyS3ObjectRole.Arn
          Runtime: nodejs6.10
          Code:
              ZipFile: >
                  var response = require('cfn-response');
                  var aws = require('aws-sdk');
                  var s3 = new aws.S3();

                  exports.handler = function(event, context) {
                    if (event.RequestType == "Create" || event.RequestType == "Update") {
                      var request = s3.copyObject( {
                        "CopySource": `${event.ResourceProperties.SourceBucket}/${event.ResourceProperties.SourceKey}`,
                        "Bucket": event.ResourceProperties.DestinationBucket,
                        "Key": event.ResourceProperties.DestinationKey
                      }, function(err, data) {
                          if (err) {
                            console.log("Error:", err, err.stack);
                            response.send(event, context, response.FAILED)
                          } else {
                            console.log("Success:", data);
                            response.send(event, context, response.SUCCESS, data)
                          }});
                    } else {
                      response.send(event, context, response.SUCCESS, {});
                    }
                  };

  CopyS3ObjectRole:
      Type: AWS::IAM::Role
      Properties:
          AssumeRolePolicyDocument:
              Version: '2012-10-17'
              Statement:
                  -
                      Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action:
                          - sts:AssumeRole
          Policies:
              -
                  PolicyName: CopyS3ObjectPolicy
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          -
                              Effect: Allow
                              Action:
                                  - logs:CreateLogGroup
                                  - logs:CreateLogStream
                                  - logs:PutLogEvents
                              Resource: arn:aws:logs:*:*:*
                          -
                              Sid: "AccessSourceAndDestinationBuckets"
                              Effect: Allow
                              Action:
                                  - s3:ListBucket
                                  - s3:ListBucketVersions
                                  - s3:GetObject
                                  - s3:GetObjectVersion
                                  - s3:PutObject
                              Resource: arn:aws:s3:::*

Outputs:
    Arn:
      Description: The arn of the custom resource function.
      Value: !GetAtt CopyS3Object.Arn
      Export:
          Name: CopyS3Object
